version: '3.8'

services:
  nimbus:
    build:
      context: .
      dockerfile: Dockerfile
    image: nimbus-service:latest
    container_name: nimbus-app
    env_file:
      - .env
    volumes:
      - nimbus_cache:/app/cache
    networks:
      - reverse-proxy
      - default
    restart: unless-stopped

volumes:
  nimbus_cache:

networks:
  reverse-proxy:
    external: true
    name: reverse-proxy

